server:
  port: 8020
  
# oauth2 config
security:
  oauth2:
    client:
      client-id: base-app
      client-secret: base-app
    resource:
      token-info-uri: http://localhost:8021/oauth/check_token
      user-info-uri: http://localhost:8021/user/current 

#spring:
#  main:#    allow-bean-definition-overriding: true
    
# eureka client config
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8022/eureka  ## 注册到 eureka 
spring:
  application:
    name: base-server  ## 应用程序名称，后面会在消费者中用到